### PR TITLE
Backend Error handling & implementation of an RGB LED

### PR DESCRIPTION
**Pull request by EthylTaco**

### CODE REVIEW

**Comment by tonogram** [comment]
LGTM! Just needs testing.

**Comment by EthylTaco** [comment]
Ok, it's good now, After we test it, we can pull it into main. Brightness doesn't work yet.

**Comment by EthylTaco** [comment]
rgb_led _Should_ be implemented properly, I tested it on the pi & added it to format.json & exec. Can we review & merge?

**Comment by tonogram** [comment]
- [ ] What is the difference between `led_bright.rs` and `pwm_led.rs`? It seems like they're trying to do the same thing, so have just one.
- [ ] `led_bright.rs`/`pwm_led.rs` is missing a duplicate function for other platforms.
- [ ] `led_bright.rs`/`pwm_led.rs` is missing a brightness parameter as input.
- [ ] `motor.rs` is missing some error handling.
- [ ] `rgb_led.rs` doesn't have any error handling at all.

**Comment by tonogram** [comment]
Also, since this PR has conflicts with the main branch (don't worry, you didn't do anything wrong) let me resolve them myself so that they can be merged.

**Comment by tonogram** [comment]
This needs to be tested before it can be merged. Keep in mind that it's still using the old UI...

**Comment by tonogram** [comment]
Merged into branch `merge-38`

**Pull request closed without merging**
